name: build image & push ecr & perview pulumi
on:
  push:
    branches:
      - master
jobs:
  preview:
    name: Preview
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          #use self-hosted runner doesn't need these
          #aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          #aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-2

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Checkout
        uses: actions/checkout@v2

      - name: Diff Lambda Code
        id: git-diff
        uses: technote-space/get-diff-action@v4
        with:
          PATTERNS: |
            handler/*.py

      - name: Build, tag, and push image to Amazon ECR
        id: push-ecr
        if: steps.git-diff.outputs.diff
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: my-ecr-repo
          IMAGE_TAG: ${{ github.sha }}
        run: |
          aws ecr describe-repositories --repository-names $ECR_REPOSITORY > /dev/null 2>&1 || \
                aws ecr create-repository --repository-name $ECR_REPOSITORY
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          mkdir -p to/artifact
          echo "${ECR_REGISTRY}/${ECR_REPOSITORY}:${IMAGE_TAG}" > to/artifact/imguri.txt
        working-directory: ./handler

      - uses: actions/upload-artifact@v2
        if: steps.git-diff.outputs.diff
        with:
          name: ecr-image-uri
          path: handler/to/artifact/imguri.txt

      - uses: pulumi/actions@v3
        with:
          command: preview
          stack-name: pulumi-aws-demo
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}