name: depoly pulumi stack

on:
  push:
    tags:
      - v0.1.*

jobs:
  build-and-push:
    runs-on: self-hosted
    steps:

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          #use self-hosted runner doesn't need these
          #aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          #aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-2

      - uses: actions/download-artifact@v2
        name: Download Lambda Image Uri
        with:
          name: ecr-image-uri

      - name: Set lambdaImage Env
        run: |
          echo "::set-output name=lambdaImage::$(imguri.txt)"

      - uses: actions/checkout@v2
        name: Checkout

      - name: Deploy Pulumi Stack To AWS
        uses: pulumi/actions@v3
        with:
          command: up
          stack-name: pulumi-aws-demo
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
          MY_EMAIL_ADDRESS: ${{ secrets.MY_EMAIL_ADDRESS }}
          IMAGE_URI: ${{ steps.push-ecr.outputs.lambdaImage }}